### ISSUE TITLE
Support for Fedora 25?

### ISSUE THREAD

**Issue by woohooatb** [drenninghoff/infinality-ultimate-fedora#20]
I am on Fedora 25 and i cannot install RPM for this. I hope you will make one soon. Thank you.

**Comment by drenninghoff** [comment]
Hi, sorry but I won't support Fedora 25. Freetype 2.7 has now implemented the v40 hinter which is similar to infinality hinting and doesn't need any configuring. With this I feel like you can finally get good font rendering with the default settings. Therefore I will stick to the stock fonts and packages that come with fedora and won't update this repository anymore. Sorry! If you feel like you need to continue using infinality, feel free to port my packages to fedora 25 and compile them yourself.

**Comment by woohooatb** [comment]
Ok. But 2.6 was better than 2.7 in my experience. This is why I wanted to install infinality in the first place. But thanks again for your quick response. :)

**Comment by yalcin** [comment]
I just built freetype-infinality-ultimate and fontconfig-infinality-ultimate packages without any change on Fedora 25 . It works fine.

**Comment by bugaevc** [comment]
@drenninghoff I've just upgraded to Fedora 25 and FreeType is on v2.6.5 or something, but not 2.7 as I thought it wold be. What gives? I've uninstalled Infinality, so it shouldn't be affecting that.

**Comment by naimarshad** [comment]
So since freetype is not on 2.7! will we get a build for fedora 25?

**Comment by bugaevc** [comment]
Or maybe just a working COPR for FreeType 2.7?

**Comment by naimarshad** [comment]
Well I've just built the reetype-infinality-ultimate and fontconfig-infinality-ultimate packages & installed accordingly. It's working fine & fonts are surely better than native freetype 2.6.5.

**Comment by yalcin** [comment]
i just switched to xorg from wayland and i added `Xft.lcdfilter: lcddefault` to `~/.Xresources` file.

vanilla freetype 2.6.5
hinting: slight
antialiasing: rgba

the result is almost awesome:
![screenshot from 2016-11-23 20-14-12](https://cloud.githubusercontent.com/assets/104388/20571686/2793d8b2-b1b1-11e6-9752-86ad91de7316.png)

**Comment by bugaevc** [comment]
@yalcin Does Quora look like this though?
![image](https://cloud.githubusercontent.com/assets/10091584/20572375/4c3e838c-b1bc-11e6-8228-02e6c7f7b10a.png)

**Comment by yalcin** [comment]
@bugaevc Upvote button doesn't work.

**Comment by naimarshad** [comment]
@bugaevc this is how it looks like with me on wayland. Hint full and droid sans as my default font.
![screenshot from 2016-11-23 22-10-17](https://cloud.githubusercontent.com/assets/15954990/20575330/4d64306a-b165-11e6-935e-d0098a74e1a2.png)

**Comment by caoli5288** [comment]
https://copr.fedorainfracloud.org/coprs/caoli5288/infinality-ultimate/

**Comment by zaps** [comment]
@caoli5288 just an FYI I tried these copr packages on a fresh Fedora 25 install. 
They installed fine and fonts look beautiful but after a reboot the system no longer boots 😢 
It hangs at the Fedora logo progress loader screen. 
If I Ctrl-Alt-F2 to a console it appears a bunch of service startups are hanging (firewalld, logind, ModemManager, etc). 
I had to use the `--allowerasing` option to dnf as indicated in @drenninghoff's [instructions](https://danielrenninghoff.com/2015/11/22/infinality-ultimate-bundle-packaged-for-fedora/) in order to get the packages to install over existing versions - I suspect there is some conflict between the 2 sets that are causing this behavior.
It's not a big deal for me, I'm just testing F25 but I wanted to bring it up in case you maybe have seen this before.

**Comment by caoli5288** [comment]
@zaps Yes? I test it for half month age and it not break my system...maybe some package changed, I'll review it

**Comment by caoli5288** [comment]
@zaps I try install fresh f25 and install infinality-ultimate from my repo with `--allowerasing` option and no system hang happen :-/
![2016-11-29 06-53-11](https://cloud.githubusercontent.com/assets/3120587/20689472/2f1c2796-b58b-11e6-8223-a29e96b89860.png)

**Comment by zaps** [comment]
@caoli5288 I got it working now -- I reinstalled F25 fresh and before installing your copr packages, switched to the "Gnome on Xorg" session at the GDM login screen instead of the default.
![Gnome on Xorg](https://cloud.githubusercontent.com/assets/2954949/20717945/30a6835a-b625-11e6-8007-f3c071cc55e6.png)

I think the Wayland server now that it is the default might be what caused my initial install to hang  -- can you confirm on your F25 that you are in an Xorg session? Thanks

**Comment by caoli5288** [comment]
@zaps I use the default wayland session and X season also work fine. Maybe the graphcard reason? I use Intel HD graphcrad

**Comment by zaps** [comment]
@caoli5288 I'm using Intel also, although its a laptop version so might not be as powerful
![image](https://cloud.githubusercontent.com/assets/2954949/20721335/733cd38a-b630-11e6-8750-9e860f3134cc.png)
In any case, Gnome on Xorg is good enough for me. Thanks for your help!

**Comment by caoli5288** [comment]
@zaps +1

**Comment by flyingpreacher** [comment]
@caoli5288 I just tried it with a NVIDIA GTX 960 and fresh Fedora 25 installation. It works great! Even with Wayland. Thanks a lot for the COPR Repo :)

**Comment by samupl** [comment]
One time I also had my fedora hanging at boot, and it turned out it was rebuilding font cache on start, which for some reason took very long time. After I let it build it never froze again. What copr repo are you guys using? Because the RPM repository no longer works (https://github.com/drenninghoff/infinality-ultimate-fedora/issues/25)

**Comment by gogoengie** [comment]
@samupl They're probably using the COPR build from @caoli5288 listed above: https://copr.fedorainfracloud.org/coprs/caoli5288/infinality-ultimate/

You have to enable COPR repos to use it, pay attention to the instructions on the right-hand side of that page.

Incidentally, thanks @caoli5288! Works great, although it does prevent `cairo-object` from updating.

**Comment by devhen** [comment]
@samupl I'm using this with great results. https://copr.fedorainfracloud.org/coprs/dawid/better_fonts/

**Comment by jonasnordlund** [comment]
This one also worked perfectly for me and Fedora 25. :)
https://copr.fedorainfracloud.org/coprs/yogurt1/freetype27/

(`dnf copr enable yogurt1/freetype27` followed by `dnf upgrade`)

Definitely similar to Infinality with Greyscale and hinting turned off. Very happy to see Linux distros getting this by default in the future.
