### ISSUE TITLE
[Question] Why doesn't use /etc/X11/Xresources directly?

### ISSUE THREAD

**Issue by simonbcn** [drenninghoff/infinality-ultimate-fedora#4]
I have installed your repository in Fedora 23 and I have installed the packages mentioned in your [blogpost](http://danielrenninghoff.com/2015/11/22/infinality-ultimate-bundle-packaged-for-fedora/).
It installs a bash script in `/etc/X11/xinit/xinitrc.d/` but would not it be better to use the file `/etc/X11/Xresources`?
I have added those lines at end of this file:

```
$ cat /etc/X11/Xresources
! This is the global resources file that is loaded when
! all users log in, as well as for the login screen

! Fix the Xft dpi to 96; this prevents tiny fonts
! or HUGE fonts depending on the screen size.
Xft.dpi: 96

! hintstyle: medium means that (for Postscript fonts) we
! position the stems for maximum constrast and consistency
! but do not force the stems to integral widths. hintnone,
! hintslight, and hintfull are the other possibilities.
! Xft.hintstyle: hintmedium
! Xft.hinting: true

Xft.antialias:  1
Xft.autohint:   0
Xft.dpi:        96
Xft.hinting:    1
Xft.hintstyle:  hintfull
Xft.lcdfilter:  lcddefault
Xft.rgba:       rgb
```

**Comment by danielrenninghoff** [comment]
Hey, thanks for using my package. It doesn't make a difference if you put it in xinitrc.d or the Xresources file. Both get loaded when the X server starts. Having stuff like this in an extra file makes package management easier. If I would replace the Xresources file, there would be a dependency conflict with the package that supplies the Xresources file. That's why different config files for different packages are used in general. Also, bohoomil uses the file in his original package, so it doesn't make sense to change it.
